CREATE  TABLE IF NOT EXISTS `employees` (
  `ID` BIGINT UNSIGNED AUTO_INCREMENT,
  `USER_ID` VARCHAR(255) NOT NULL,
  `ORDER_ID` VARCHAR(255) NOT NULL,
  `ZOHO_ID` VARCHAR(255) NOT NULL,
  `PRICE` INT DEFAULT 0,
  `CREATED_AT` DATETIME NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;